'use strict';
const nodeRedis=require('redis');
const genio=require('../lib');
const client=nodeRedis.createClient();
genio(function*(){
    let val;
    console.log('creating context from Redis client');
    const redis=new genio.Context(client);
    console.log(redis);
    console.log('compiled Redis client');
    console.log(require('util').inspect(redis));
    console.log('context is ', redis);
    val='works with Redis';
    yield redis.set('gen-io',val);
    console.log('set value');
    val=yield redis.get('gen-io');
    console.log('get value');
    console.log(`gen-io ${val}`);
    process.exit(0);
});